### ISSUE TITLE
suggestion: use r-lib/desc to parse from DESCRIPTION files

### ISSUE THREAD

**Issue by ha0ye** [ocbe-uio/RCFF#12]
There is an existing package to parse DESCRIPTION files over at https://github.com/r-lib/desc . 

I think it would be effective to build off of that work for (at least) the parsing component, to avoid reinventing the wheel, and to keep functionality modular: so that desc interacts with DESCRIPTION files, and this package spits out a correctly formatted CFF.

**Comment by wleoncio** [comment]
Thank you, it sounds like a good idea. I'll check it out and see what is the most reasonable course of action.
